name: Application Destroy

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} 
  TF_WORKSPACE: "helops-test" 
  CONFIG_DIRECTORY: "./terraform"

#using-an-action
jobs:
  terraform-cloud-destroy-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    # permissions:
    #   pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve